### create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john6@example.com",
  "password": "securepassword",
  "gender":"male"
}


### login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john6@example.com",
  "password": "securepassword"
}
